### ISSUE TITLE
Can you give me an example how to fetch the whole option chain from an option?

### ISSUE THREAD

**Issue by gamebak** [maxicus/ib-tws-api#1]
**The problem:**
With [your example](https://github.com/maxicus/ib-tws-api/blob/master/examples/contract-options.js) I'm able to see the available expirations + strikes, but not the full option chain with puts/calls side by side. 

The problem is that I'll end up with a lot of requests just to see an option chain. The nr of individual requests = 2 * nr of strikes per expiration which is a lot. 

There should be a better way to do this, from a single call, in the TWS API I found this: https://interactivebrokers.github.io/tws-api/options.html#option_chains

**Potential solution:**
What I've tried was to manually "bruteforce" my way into Contract. options removing the asserts and to add the localSymbol, but that actually generated more problems. 

**Can you help me with an example of how I could get the option chain without doing individual requests for every strike?**

**Comment by gamebak** [comment]
I've tested this, but sadly the option chain is still missing bid/ask dates, so I assume the only way to get those is to connect to each strike and get a stream.

Thanks for the effort!

**Comment by maxicus** [comment]
Of course, this is only to get a list of instruments.
Still useful since prevents from checking against the whole matrix of strike/expirations (SecDefOptParams output).
