### ISSUE TITLE
Scanners

### ISSUE THREAD

**Issue by joseraul** [maxicus/ib-tws-api#10]
Hi!

I think the scanners are not implemented, right?
I would like to create a PR if you point me in the correct direction.

Thanks!

**Comment by maxicus** [comment]
hi, i see some start of the work there but never needed it, so not finished.

should be very to similar to getHistoricalData or streamMarketData.

reqScannerSubscription becomes e.g. scannerSubscription, where you allocate requestId and use packing code to make a request.

**Comment by joseraul** [comment]
You have a PR 😄
In fact, you already did all the work: https://github.com/maxicus/ib-tws-api/pull/11

**Comment by joseraul** [comment]
@maxicus , do you know how to know the name of the events?
I think the subscription needs to be opened, so I change the connection to:

```
    await this._sendFieldsetRateLimited(flds);

    return this._incomeHandler.requestIdEmitter(requestId, () => {
      this.cancelScannerSubscription(requestId);
    });
```

however `tick` returns nothing

```
    e.on('tick', (t) => {
        console.log(t);
    });
```

and I really can't find the event names anywhere... do you know how to spot them thanks!

**Comment by joseraul** [comment]
Forget what I said 🤦 I need to emit the event myself. PR Ready! https://github.com/maxicus/ib-tws-api/pull/11 
Thanks!

**Comment by maxicus** [comment]
@joseraul Thanks for your participation.
