### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by tredondo** [maxicus/ib-tws-api#15]
Given the complexity of IB classes, TypeScript type information would be tremendously useful for this package.

Would you be interested in a contribution that converted the code to TypeScript and added type annotations and documentation?

**Comment by maxicus** [comment]
Hi,

This package will stay pure javascript.
You may add mapping or docs - those are welcome.
But no code conversion.

**Comment by tredondo** [comment]
OK with no code conversion.

What I (and I assume many others) would find extremely useful is type definitions. For example, right now, IDEs have no way of suggesting the parameters for `Contract`s. [`symbolOrData`](https://github.com/maxicus/ib-tws-api/blob/master/contract.js#L15) has no type information.

There's also no type definition for the results of methods (and every dev has to discover them manually, as I had to do with `getHistoricalData` in #19.

**Comment by maxicus** [comment]
It's just not a typescript project (hope you've seen the first line of readme file).
Personally I don't IDEs for last 15 years so can't value how good or bad it is. And naturally can't maintain things related to it (for free).

Anyway I'm fine with any metadata, including jsdocs you already posted, which won't add ANY extra complexity.
Even added some jsdocs myself...

So, /ts/ folder with all that ts crap and pointer to it from module file is just fine :)

**Comment by tredondo** [comment]
Re. how good TypeScript or IDEs are, a quick practical example is that either of these tools would have caught that [undefined variable](https://github.com/maxicus/ib-tws-api/pull/21).

Undefined variables can trivially be detected by static analysis nowadays and should really not show up in high-quality code.

Hello from 2021 ;)

**Comment by tredondo** [comment]
Hello. Is this package still maintained?

**Comment by maxicus** [comment]
yes, its functional

**Comment by tredondo** [comment]
Nice, any change in plans regarding accepting TypeScript contributions?

IMO, "I haven't used IDEs in the last 15 years" is fine as a personal choice, but hurts/pushes away the vast majority of developers would might otherwise be very interested in this project.
