### ISSUE TITLE
Example listening to events like orderStatus

### ISSUE THREAD

**Issue by tredondo** [maxicus/ib-tws-api#22]
[placeOrder](https://github.com/maxicus/ib-tws-api/blob/master/client.js#L594-L597) says "The order status will be returned by the orderStatus event." How [exactly](https://github.com/maxicus/ib-tws-api/blob/master/examples/order.js#L32) should we listen to that event? placeOrder returns a `number`, not an EventEmitter.

**Comment by maxicus** [comment]
Good point.
Added public method for that.
see https://github.com/maxicus/ib-tws-api/commit/137e0af349d53d415a8b203096c1c349e72268a9

event itself:
```
this.emit('orderStatus', {
      orderId: orderId,
      status: status,
      filled: filled,
      remaining: remaining,
      avgFillPrice: avgFillPrice,
      permId: permId,
      parentId: parentId,
      lastFillPrice: lastFillPrice,
      clientId: clientId,
      whyHeld: whyHeld,
      marketCapPrice: marketCapPrice
    });
```
